/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam;


import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import pl.poznan.uam.tables.Chairs;
import pl.poznan.uam.tables.Sets;
import pl.poznan.uam.tables.Tables;
import pl.poznan.uam.tables.records.ChairsRecord;
import pl.poznan.uam.tables.records.SetsRecord;
import pl.poznan.uam.tables.records.TablesRecord;


/**
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    public static final Identity<ChairsRecord, Integer> IDENTITY_CHAIRS = Identities0.IDENTITY_CHAIRS;
    public static final Identity<SetsRecord, Integer> IDENTITY_SETS = Identities0.IDENTITY_SETS;
    public static final Identity<TablesRecord, Integer> IDENTITY_TABLES = Identities0.IDENTITY_TABLES;

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<ChairsRecord> CHAIRS_PKEY = UniqueKeys0.CHAIRS_PKEY;
    public static final UniqueKey<SetsRecord> SETS_PKEY = UniqueKeys0.SETS_PKEY;
    public static final UniqueKey<TablesRecord> TABLES_PKEY = UniqueKeys0.TABLES_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<SetsRecord, ChairsRecord> SETS__CHAIR_ID = ForeignKeys0.SETS__CHAIR_ID;
    public static final ForeignKey<SetsRecord, TablesRecord> SETS__TABLE_ID = ForeignKeys0.SETS__TABLE_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Identities0 extends AbstractKeys {
        public static Identity<ChairsRecord, Integer> IDENTITY_CHAIRS = createIdentity(Chairs.CHAIRS, Chairs.CHAIRS.ID);
        public static Identity<SetsRecord, Integer> IDENTITY_SETS = createIdentity(Sets.SETS, Sets.SETS.ID);
        public static Identity<TablesRecord, Integer> IDENTITY_TABLES = createIdentity(Tables.TABLES, Tables.TABLES.ID);
    }

    private static class UniqueKeys0 extends AbstractKeys {
        public static final UniqueKey<ChairsRecord> CHAIRS_PKEY = createUniqueKey(Chairs.CHAIRS, "chairs_pkey", Chairs.CHAIRS.ID);
        public static final UniqueKey<SetsRecord> SETS_PKEY = createUniqueKey(Sets.SETS, "sets_pkey", Sets.SETS.ID);
        public static final UniqueKey<TablesRecord> TABLES_PKEY = createUniqueKey(Tables.TABLES, "tables_pkey", Tables.TABLES.ID);
    }

    private static class ForeignKeys0 extends AbstractKeys {
        public static final ForeignKey<SetsRecord, ChairsRecord> SETS__CHAIR_ID = createForeignKey(pl.poznan.uam.Keys.CHAIRS_PKEY, Sets.SETS, "sets__chair_id", Sets.SETS.CHAIR_ID);
        public static final ForeignKey<SetsRecord, TablesRecord> SETS__TABLE_ID = createForeignKey(pl.poznan.uam.Keys.TABLES_PKEY, Sets.SETS, "sets__table_id", Sets.SETS.TABLE_ID);
    }
}
