/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam;


import javax.annotation.Generated;

import pl.poznan.uam.tables.Chairs;
import pl.poznan.uam.tables.Sets;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.chairs</code>.
     */
    public static final Chairs CHAIRS = pl.poznan.uam.tables.Chairs.CHAIRS;

    /**
     * The table <code>public.sets</code>.
     */
    public static final Sets SETS = pl.poznan.uam.tables.Sets.SETS;

    /**
     * The table <code>public.tables</code>.
     */
    public static final pl.poznan.uam.tables.Tables TABLES = pl.poznan.uam.tables.Tables.TABLES;
}
