/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import pl.poznan.uam.tables.Chairs;
import pl.poznan.uam.tables.records.ChairsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ChairsDao extends DAOImpl<ChairsRecord, pl.poznan.uam.tables.pojos.Chairs, Integer> {

    /**
     * Create a new ChairsDao without any configuration
     */
    public ChairsDao() {
        super(Chairs.CHAIRS, pl.poznan.uam.tables.pojos.Chairs.class);
    }

    /**
     * Create a new ChairsDao with an attached configuration
     */
    public ChairsDao(Configuration configuration) {
        super(Chairs.CHAIRS, pl.poznan.uam.tables.pojos.Chairs.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(pl.poznan.uam.tables.pojos.Chairs object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Chairs> fetchById(Integer... values) {
        return fetch(Chairs.CHAIRS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public pl.poznan.uam.tables.pojos.Chairs fetchOneById(Integer value) {
        return fetchOne(Chairs.CHAIRS.ID, value);
    }

    /**
     * Fetch records that have <code>height IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Chairs> fetchByHeight(Integer... values) {
        return fetch(Chairs.CHAIRS.HEIGHT, values);
    }

    /**
     * Fetch records that have <code>width IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Chairs> fetchByWidth(Integer... values) {
        return fetch(Chairs.CHAIRS.WIDTH, values);
    }

    /**
     * Fetch records that have <code>color IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Chairs> fetchByColor(String... values) {
        return fetch(Chairs.CHAIRS.COLOR, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Chairs> fetchByName(String... values) {
        return fetch(Chairs.CHAIRS.NAME, values);
    }
}
