/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam.tables.daos;


import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;

import pl.poznan.uam.tables.Tables;
import pl.poznan.uam.tables.records.TablesRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TablesDao extends DAOImpl<TablesRecord, pl.poznan.uam.tables.pojos.Tables, Integer> {

    /**
     * Create a new TablesDao without any configuration
     */
    public TablesDao() {
        super(Tables.TABLES, pl.poznan.uam.tables.pojos.Tables.class);
    }

    /**
     * Create a new TablesDao with an attached configuration
     */
    public TablesDao(Configuration configuration) {
        super(Tables.TABLES, pl.poznan.uam.tables.pojos.Tables.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(pl.poznan.uam.tables.pojos.Tables object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Tables> fetchById(Integer... values) {
        return fetch(Tables.TABLES.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public pl.poznan.uam.tables.pojos.Tables fetchOneById(Integer value) {
        return fetchOne(Tables.TABLES.ID, value);
    }

    /**
     * Fetch records that have <code>height IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Tables> fetchByHeight(Integer... values) {
        return fetch(Tables.TABLES.HEIGHT, values);
    }

    /**
     * Fetch records that have <code>width IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Tables> fetchByWidth(Integer... values) {
        return fetch(Tables.TABLES.WIDTH, values);
    }

    /**
     * Fetch records that have <code>lenght IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Tables> fetchByLenght(Integer... values) {
        return fetch(Tables.TABLES.LENGHT, values);
    }

    /**
     * Fetch records that have <code>shape IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Tables> fetchByShape(String... values) {
        return fetch(Tables.TABLES.SHAPE, values);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<pl.poznan.uam.tables.pojos.Tables> fetchByName(String... values) {
        return fetch(Tables.TABLES.NAME, values);
    }
}
