/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam.tables;


import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;

import pl.poznan.uam.Keys;
import pl.poznan.uam.Public;
import pl.poznan.uam.tables.records.SetsRecord;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.9.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sets extends TableImpl<SetsRecord> {

    private static final long serialVersionUID = 1870184041;

    /**
     * The reference instance of <code>public.sets</code>
     */
    public static final Sets SETS = new Sets();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SetsRecord> getRecordType() {
        return SetsRecord.class;
    }

    /**
     * The column <code>public.sets.id</code>.
     */
    public final TableField<SetsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('sets_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.sets.chair_id</code>.
     */
    public final TableField<SetsRecord, Integer> CHAIR_ID = createField("chair_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sets.table_id</code>.
     */
    public final TableField<SetsRecord, Integer> TABLE_ID = createField("table_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.sets.name</code>.
     */
    public final TableField<SetsRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

    /**
     * Create a <code>public.sets</code> table reference
     */
    public Sets() {
        this("sets", null);
    }

    /**
     * Create an aliased <code>public.sets</code> table reference
     */
    public Sets(String alias) {
        this(alias, SETS);
    }

    private Sets(String alias, Table<SetsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Sets(String alias, Table<SetsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<SetsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_SETS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<SetsRecord> getPrimaryKey() {
        return Keys.SETS_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<SetsRecord>> getKeys() {
        return Arrays.<UniqueKey<SetsRecord>>asList(Keys.SETS_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<SetsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<SetsRecord, ?>>asList(Keys.SETS__CHAIR_ID, Keys.SETS__TABLE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Sets as(String alias) {
        return new Sets(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Sets rename(String name) {
        return new Sets(name, null);
    }
}
