/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam.tables.pojos;


import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import pl.poznan.uam.tables.interfaces.IChairs;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Chairs implements IChairs {

    private static final long serialVersionUID = -1210628101;

    private Integer id;
    private Integer height;
    private Integer width;
    private String  color;
    private String  name;

    public Chairs() {}

    public Chairs(Chairs value) {
        this.id = value.id;
        this.height = value.height;
        this.width = value.width;
        this.color = value.color;
        this.name = value.name;
    }

    public Chairs(
        Integer id,
        Integer height,
        Integer width,
        String  color,
        String  name
    ) {
        this.id = id;
        this.height = height;
        this.width = width;
        this.color = color;
        this.name = name;
    }

    @Override
    public Integer getId() {
        return this.id;
    }

    @Override
    public Chairs setId(Integer id) {
        this.id = id;
        return this;
    }

    @NotNull
    @Override
    public Integer getHeight() {
        return this.height;
    }

    @Override
    public Chairs setHeight(Integer height) {
        this.height = height;
        return this;
    }

    @NotNull
    @Override
    public Integer getWidth() {
        return this.width;
    }

    @Override
    public Chairs setWidth(Integer width) {
        this.width = width;
        return this;
    }

    @NotNull
    @Size(max = 64)
    @Override
    public String getColor() {
        return this.color;
    }

    @Override
    public Chairs setColor(String color) {
        this.color = color;
        return this;
    }

    @NotNull
    @Size(max = 64)
    @Override
    public String getName() {
        return this.name;
    }

    @Override
    public Chairs setName(String name) {
        this.name = name;
        return this;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Chairs (");

        sb.append(id);
        sb.append(", ").append(height);
        sb.append(", ").append(width);
        sb.append(", ").append(color);
        sb.append(", ").append(name);

        sb.append(")");
        return sb.toString();
    }

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public void from(IChairs from) {
        setId(from.getId());
        setHeight(from.getHeight());
        setWidth(from.getWidth());
        setColor(from.getColor());
        setName(from.getName());
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public <E extends IChairs> E into(E into) {
        into.from(this);
        return into;
    }
}
