/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ISets extends Serializable {

    /**
     * Setter for <code>public.sets.id</code>.
     */
    public ISets setId(Integer value);

    /**
     * Getter for <code>public.sets.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.sets.chair_id</code>.
     */
    public ISets setChairId(Integer value);

    /**
     * Getter for <code>public.sets.chair_id</code>.
     */
    @NotNull
    public Integer getChairId();

    /**
     * Setter for <code>public.sets.table_id</code>.
     */
    public ISets setTableId(Integer value);

    /**
     * Getter for <code>public.sets.table_id</code>.
     */
    @NotNull
    public Integer getTableId();

    /**
     * Setter for <code>public.sets.name</code>.
     */
    public ISets setName(String value);

    /**
     * Getter for <code>public.sets.name</code>.
     */
    @Size(max = 64)
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ISets
     */
    public void from(pl.poznan.uam.tables.interfaces.ISets from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ISets
     */
    public <E extends pl.poznan.uam.tables.interfaces.ISets> E into(E into);
}
