/*
 * This file is generated by jOOQ.
*/
package pl.poznan.uam.tables.interfaces;


import java.io.Serializable;

import javax.annotation.Generated;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.0"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITables extends Serializable {

    /**
     * Setter for <code>public.tables.id</code>.
     */
    public ITables setId(Integer value);

    /**
     * Getter for <code>public.tables.id</code>.
     */
    public Integer getId();

    /**
     * Setter for <code>public.tables.height</code>.
     */
    public ITables setHeight(Integer value);

    /**
     * Getter for <code>public.tables.height</code>.
     */
    @NotNull
    public Integer getHeight();

    /**
     * Setter for <code>public.tables.width</code>.
     */
    public ITables setWidth(Integer value);

    /**
     * Getter for <code>public.tables.width</code>.
     */
    @NotNull
    public Integer getWidth();

    /**
     * Setter for <code>public.tables.lenght</code>.
     */
    public ITables setLenght(Integer value);

    /**
     * Getter for <code>public.tables.lenght</code>.
     */
    @NotNull
    public Integer getLenght();

    /**
     * Setter for <code>public.tables.shape</code>.
     */
    public ITables setShape(String value);

    /**
     * Getter for <code>public.tables.shape</code>.
     */
    @NotNull
    @Size(max = 64)
    public String getShape();

    /**
     * Setter for <code>public.tables.name</code>.
     */
    public ITables setName(String value);

    /**
     * Getter for <code>public.tables.name</code>.
     */
    @NotNull
    @Size(max = 65)
    public String getName();

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Load data from another generated Record/POJO implementing the common interface ITables
     */
    public void from(pl.poznan.uam.tables.interfaces.ITables from);

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITables
     */
    public <E extends pl.poznan.uam.tables.interfaces.ITables> E into(E into);
}
